packages:
  - name: updownio-to-pushover
    actions:
      - name: updownio-to-pushover
        runtime: nodejs:default
        web: true
        environment:
          PUSHOVER_USER: ${PUSHOVER_USER}
          PUSHOVER_TOKEN: ${PUSHOVER_TOKEN}
        limits:
          memory: 128
          timeout: 3000
